{
   "widgets": [
       {
          "type":"metric",
          "properties":{
             "metrics":[
                [
                   "AWS/EC2",
                   "CPUUtilization",
                   "InstanceId",
                   "${instance_id}"
                ]
             ],
             "period":300,
             "stat":"Average",
             "region":"${region}",
             "title":"CPU utilization"
          }
       },
       {
          "type":"metric",
          "properties":{
             "metrics":[
                [
                   "System/Linux",
                   "MemoryUtilization",
                   "InstanceId",
                   "${instance_id}"
                ]
             ],
             "period":300,
             "stat":"Average",
             "region":"${region}",
             "title":"Memory utilization"
          }
       },
       {
          "type":"metric",
          "properties":{
             "metrics":[
                [
                   "System/Linux",
                   "DiskSpaceUtilization",
                   "InstanceId",
                   "${instance_id}",
                   "MountPath",
                   "/"
                ],
                [
                   "System/Linux",
                   "DiskSpaceUtilization",
                   "InstanceId",
                   "${instance_id}",
                   "MountPath",
                   "/data"
                ]
             ],
             "period":300,
             "stat":"Average",
             "region":"${region}",
             "title":"Disk utilization"
          }
       }
   ]
 }